INSERT INTO departments(dept_name, college, building) VALUES
("Department of Anthropology","College of Arts and Sciences", 1000),
("School of Advertising and Mass Communications","College of Arts and Sciences", 2000),
("Department of Cell Biology, Microbiology, and Molecular Biology","College of Arts and Sciences",3000),
("Department of Chemistry","College of Arts and Sciences",4000),
("Department of Communication","College of Arts and Sciences",5000),
("Department of Economics","College of Arts and Sciences",6000),
("Department of English","College of Arts and Sciences",7000),
("School of Geosciences","College of Arts and Sciences",8000),
("Department of History","College of Arts and Sciences",9000),
("Department of Humanities and Cultural Studies","College of Arts and Sciences",10000),
("School of Information","College of Arts and Sciences",11000),
("Department of Integrative Biology","College of Arts and Sciences",12000),
("School of Interdisciplinary Global Studies","College of Arts and Sciences",13000),
("Department of Journalism and Digital Communication","College of Arts and Sciences",14000),
("Department of Mathematics and Statistics","College of Arts and Sciences",15000),
("Department of Physics","College of Arts and Sciences",16000),
("Department of Philosophy","College of Arts and Sciences",17000),
("Department of Psychology","College of Arts and Sciences",18000),
("School of Public Affairs","College of Arts and Sciences",19000),
("Department of Religious Studies","College of Arts and Sciences",20000),
("Department of Sociology and Interdisciplinary Social Sciences","College of Arts and Sciences",21000),
("Department of Women’s and Gender Studies","College of Arts and Sciences",22000),
("Department of World Languages","College of Arts and Sciences",23000),
("School of Aging Studies","College of Behavioral and Community Sciences",24000),
("Department of Child and Family Studies","College of Behavioral and Community Sciences",25000),
("Department of Communication Sciences and Disorders","College of Behavioral and Community Sciences",26000),
("Department of Criminology","College of Behavioral and Community Sciences",27000),
("Department of Mental Health Law and Policy","College of Behavioral and Community Sciences",28000),
("School of Social Work","College of Behavioral and Community Sciences",29000),
("School of Accountancy","College of Business",30000),
("School of Business and Finance","College of Business",31000),
("School of Hospitality and Tourism Management","College of Business",32000),
("School of Information Systems and Management","College of Business",33000),
("School of Marketing and Innovation","College of Business",34000),
("School of Risk Management and Insurance","College of Business",35000),
("Department of Curriculum, Instruction, and Learning","College of Education",36000),
("Department of Educational and Psychological Studies","College of Education",37000),
("Department of Leadership, Policy, and Lifelong Learning","College of Education",38000),
("Department of Language, Literacy, Ed.D., Exceptional Education","College of Education",39000),
("Department of Chemical, Biological, and Materials Engineering","College of Engineering",40000),
("Department of Civil and Environmental Engineering","College of Engineering",41000),
("Department of Computer Science and Engineering","College of Engineering",42000),
("Department of Electrical Engineering","College of Engineering",43000),
("Department of Industrial and Management Systems Engineering","College of Engineering",44000),
("Department of Mechanical Engineering","College of Engineering",45000),
("Department of Medical Engineering","College of Engineering",46000),
("Department of Nursing","College of Nursing",47000),
("Department of Public Health","College of Public Health",48000),
("School of Art and Art History","College of The Arts",49000),
("School of Music","College of The Arts",50000),
("School of Theatre and Dance","College of The Arts",51000),
("Department of Military Studies","College of Military Studies", 52000),
("Department of Sports and Physical Health", "College of Sports", 53000),
("School of Policy and Law", "College of Arts and Sciences", 54000);
